---@meta
-- Generated by hand from src/app/lua_game_api.cxx; test/lua_api_stubs_test.cxx keeps the names in sync.

---@class scene
scene = {}

---Creates an entity with the given name and an identity transform.
---@param name string
---@return Entity
function scene.spawn(name) end

---Finds an entity by name (the first match), or nil.
---@param name string
---@return Entity?
function scene.find(name) end

---Destroys every entity in the scene.
function scene.clear() end

---Adds a compute effect to a point of the frame. An effect can be in one slot at a time. Raises an error if the
---effect needs something the slot does not have (scene_colour exists from "after_lighting", scene_depth from
---"after_depth"), or lacks a buffer.
---@param effect Effect
---@param slot EffectSlot
function scene.add_effect(effect, slot) end

---Takes an effect out of its slot. It can be added again.
---@param effect Effect
function scene.remove_effect(effect) end

---Where in the frame an effect runs.
---@alias EffectSlot
---| "frame_start" # before any engine pass; no scene images yet
---| "after_depth" # scene_depth is final
---| "after_lighting" # scene_colour exists
---| "before_composite" # after bloom; the last place to replace the scene colour
